---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: jenkins-storage  # Use the new StorageClass name
  nfs:
    path: "/data/app1"
    server: "10.0.0.135"
    readOnly: false

