---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-storage
  namespace: jenkins
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
  onDelete: retain
allowVolumeExpansion: true

